version: '3'

services:
  chainlit:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data
      - ./storage:/app/storage
      - ./app:/app
    env_file:
      - .env
  postgres:
    build:
      context: .
      dockerfile: Dockerfile.postgres
    ports:
      - 5432:5432
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    env_file:
      - .env